project:
  type: website

website:
  title: "Proj CLI"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Configuration"
        contents:
          - configuration.qmd
      - section: "Build Reference"
        contents:
          - flow.qmd
      - section: "CLI Reference"
        contents:
          - cli/version.qmd
          - cli/yml.qmd
          - cli/path.qmd
          - cli/ignore.qmd

format:
  html:
    theme: cosmo
    toc: true
